Minifix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -147,7 +147,7 @@ jobs:
     - name: Ensure LHCI config files
       run: |
         test -f .lighthouserc.json || { echo "Missing .lighthouserc.json"; exit 1; }
-        test -f desktopConfig.json || { echo "Missing desktopConfig.json"; exit 1; }
+        test -f .desktopConfig.json || { echo "Missing .desktopConfig.json"; exit 1; }
 
     - name: Serve site
       run: |
